fastapi:
  url: http://localhost:8000
spring:
  datasource:
    url: jdbc:mysql://project-db-campus.smhrd.com:3307/campus_24K_LI2_p3_2?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: campus_24K_LI2_p3_2
    password: smhrd2
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ZKaZpBQ88jGwN0zuYf87
            client-secret: HgWGF91z4C
            redirect-uri: http://localhost:8083/login/oauth2/code/naver
            #redirect-uri: https://view-it.co.kr/login/oauth2/code/naver

            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
app:
  jwt:
    secret: ThisIsASecretKeyThatIsAtLeast32BytesLong!!
    expiration-ms: 3600000            # 만료 시간(ms 단위)

logging:
  level:
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

