spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ZKaZpBQ88jGwN0zuYf87
            client-secret: HgWGF91z4C
            redirect-uri: http://localhost:8083/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  jwt:
    secret: verySecretKeyHere       # 토큰 서명에 사용할 비밀키
    expiration: 3600000             # 만료 시간(ms 단위)
